export const PROVIDER_DOMAIN_ALLOWLIST: Record<string, string[]> = {
    netflix: ['netflix.com'],
    prime: ['primevideo.com', 'amazon.com'],
    appletv: ['tv.apple.com', 'itunes.apple.com'],
    hbomax: ['hbomax.com', 'max.com'],
    hulu: ['hulu.com'],
    disneyplus: ['disneyplus.com', 'hotstar.com'],
    paramountplus: ['paramountplus.com'],
    peacock: ['peacocktv.com'],
    mubi: ['mubi.com'],
    crunchyroll: ['crunchyroll.com'],
    youtube: ['youtube.com', 'youtu.be'],
    googleplay: ['play.google.com'],
    vudu: ['vudu.com'],
    rakuten: ['rakuten.tv'],
    now: ['nowtv.com', 'nowtv.it', 'nowtv.de', 'nowtv.ie', 'nowtv.es'],
    skyshowtime: ['skyshowtime.com'],
    stan: ['stan.com.au'],
    crave: ['crave.ca'],
    zee5: ['zee5.com'],
    pluto: ['pluto.tv'],
};
